apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: remyinthecloud
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: argocd.remyinthecloud.com
        service: https://ingress-nginx-controller.ingress-nginx:443
        originRequest:
          noTLSVerify: true
      - service: http_status:404
