- name: Loading Master Node IP
  hosts: localhost
  tasks:
    - name: Load Control Node Secrets
      ansible.builtin.include_vars:
        file: ~/dev/k8shomelab/ansible/host_vars/control_node.yml
        name: master

- name: Setting up K3s on Master
  hosts: k3s_master
  become: true
  vars:
    ansible_become_password: "{{ hostvars['localhost']['master']['ansible_password'] }}"
  tasks:
    - name: Installing k3s on Control Node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash

    - name: Grabbing Node Token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_encoded
    
- name: Loading Worker Node 1 IP
  hosts: localhost
  tasks:
    - name: Load Worker Node 1 Secrets
      ansible.builtin.include_vars:
        file: ~/dev/k8shomelab/ansible/host_vars/worker_node1.yml
        name: worker_node1

- name: Joining Worker Node
  hosts: k3s_worker
  become: true
  vars:
    ansible_become_password: "{{ hostvars['localhost']['worker_node1']['ansible_password'] }}"
  tasks:
    - name: Install k3s Script
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://"{{ hostvars['localhost']['master'] }}"":6443 K3S_TOKEN="{{ hostvars['k3s_master']['node_token_encoded'] | b64decode }}"" sh -