- name: Setting up K3s on Master
  hosts: k3s_master
  tasks:
    - name: Installing k3s on Control Node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
      become: true

    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/baki/.kube
        state: directory
        owner: baki
        group: baki
        mode: '0755'
      become: true

    - name: Copy kubeconfig to user home
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/baki/.kube/config
        owner: baki
        group: baki
        mode: '0600'
        remote_src: true
      become: true

    - name: Set KUBECONFIG env var
      ansible.builtin.lineinfile:
        path: /home/baki/.bashrc
        line: 'export KUBECONFIG=/home/baki/.kube/config'

    - name: Grabbing Node Token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_encoded
      become: true
    
    - name: Store Token Node
      set_fact:
        node_token: "{{ node_token_encoded['content'] | b64decode | trim }}"

- name: Joining Worker Node
  hosts: k3s_worker
  tasks:
    - name: Install k3s Script on Worker
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_node']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['control_node']['node_token'] }} sh -
      become: true